---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install pax package"
  block:
    - name: "Install pax, if not already installed (RHEL7)"
      package:
        name: 'pax'
        state: present
      when:
        - "'pax' not in ansible_facts.packages"
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '7'
    - name: "Install pax, if not already installed (RHEL8)"
      package:
        name: 'spax'
        state: present
      when:
        - "'spax' not in ansible_facts.packages"
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'

- name: "Disable SELinux"
  selinux:
    state: disabled
  register: reboot

- name: "Reboot host, after disabling SELinux"
  reboot:
  when: reboot.reboot_required

- name: "Install required library packages"
  block:
    - name: "Install required libraries, if not already installed (RHEL8)"
      package:
        name: "{{ item }}"
        state: present
      when:
        - "item|string not in ansible_facts.packages"
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'
      with_items:
        - glibc.i686
        - libgcc.i686
        - libstdc++.i686
        - glibc-devel.i686

- name: "Setup Service Account"
  block:
    - name: "Install Korn Shell, if not already installed"
      package:
        name: 'ksh'
        state: present
      when: "'ksh' not in ansible_facts.packages"
    - name: "Check for service users homedir existence"
      stat:
        path: "{{ service_homedir }}"
      register: path
    - name: "Create service users group, if not already created"
      ansible.builtin.group:
        name: "{{ service_group }}"
        state: present
      register: group
    - name: "Create service user, if not already created"
      ansible.builtin.user:
        name: "{{ service_user }}"
        group: "{{ service_group }}"
        home: "{{ service_homedir }}/{{ service_user }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_comment: "{{ service_user }}@{{ inventory_hostname }}"
        state: present
      when:
        - group.state
        - path.stat.exists
        - path.stat.isdir

- name: "Create required directories in the service users homedir"
  file:
    path: "{{ service_homedir }}/{{ service_user }}/{{ item }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    state: directory
  with_items:
    - "data"
    - "data/tmp"
    - "udata"
    - "udata/tmp"
  when:
    - path.stat.exists
    - path.stat.isdir

- name: "Check if Java Development Kit version 11 is installed"
  package:
    name: 'java-11-openjdk'
    #Oracle's JDK package = 'jdk-11.0.11'
    state: present
  when:
    - "'java-11-openjdk' not in ansible_facts.packages"
    # for Oracle's JDK package, uncomment the later & comment the prior
    #- "'jdk-11.0.11' not in ansible_facts.packages"