---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install pax, if not already installed (RHEL7)"
  package:
    name: 'pax'
    state: present
  when:
    - "'pax' not in ansible_facts.packages"
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version <= '7'

- name: "Install pax, if not already installed (RHEL8)"
  package:
    name: 'spax'
    state: present
  when:
    - "'spax' not in ansible_facts.packages"
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'

- name: "Disable SELinux"
  selinux:
    state: disabled
  register: reboot

- name: "Reboot host, after disabling SELinux"
  reboot:
  when: reboot.reboot_required
